config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'registrarse'}
  get 'user/cursos', to: 'users#myCourses', as: 'users_courses'
  get 'users', to: 'users#index', as: 'users_index'
  get 'users/:id/rol', to: 'users#rol', as: 'users_change_rol'
  get 'users/:id/asignar_curso', to: 'users#assign', as: 'users_assign_course'
  patch 'users/:id/asignacion_curso', to: 'users#do_assign', as: 'users_do_assign'
  get 'users/:id/desasignar_curso', to: 'users#unassign', as: 'users_unassign_course'
  patch 'users/:id/desasignacion_curso', to: 'users#do_unassign', as: 'users_do_unassign'

  get 'schedules/new' => 'schedules#new'
  get 'schedules/deleteAssignation' => 'schedules#deleteAssignation'
  get 'schedules/deleteAssignation/do'=> 'schedules#deleteAssignationDo'
  post 'schedules/create' => 'schedules#create'

  get 'asignaciones'          => 'assignations#select'
  get 'asignaciones/ver'      => 'assignations#show'
  get 'asignaciones/generar'  => 'assignations#generate'
  get 'asignaciones/manual'   => 'assignations#manual_select'
  get 'asignaciones/manual/do'=> 'assignations#manual_do'

  root 'pages#main'

  get 'json/downloadCourses' => 'json#downloadCourses'
  get 'json/downloadClassrooms' => 'json#downloadClassrooms'
  get 'json/downloadSchedules' => 'json#downloadSchedules'
  get 'json/databaseLoad' => 'json#databaseLoad'

  get 'consultas'             => 'consults#index'
  get 'consultas/sala/curso'  => 'consults#classroomByCourseOrSchedule'
  get 'consultas/curso/sala'  => 'consults#courseByClassroomAndSchedule'
  get 'salas/informacion'     => 'consults#show_information'

  get 'estadisticas/'  => 'statistics#show'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :courses
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
  	self.role ||= :user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def myCourses
    @assignation_teacher = Array.new
    @courses = Array.new
    current_user.courses.each do |course|
      @courses << course.nrc.to_s
    end
    Assignation.all.each do |assignation|
      schedule = Schedule.find(assignation[:schedule_id])
      if @courses.include?(schedule[:nrc].to_s)
        classroom = Classroom.find(assignation[:classroom_id])
        course = Course.find_by nrc: schedule[:nrc]
        dato = {:course => course, :schedule => schedule, :classroom =>classroom, :assignation =>assignation}
        @assignation_teacher << dato
      end
    end
  end


  def index
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    @users = User.all
  end

  def rol
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    user = User.find(params[:id])
    if user.admin?
      user.user!
    else
      user.admin!
    end
    respond_to do |format|
        format.html { redirect_to users_index_path, :notice =>'Cambio realizado con éxito'}
    end
  end

  def assign
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    @user = User.find(params[:id])
    @courses = Array.new
    Course.all.each do |course|
      if course.user_id.nil?
        @courses << [course.nrc.to_s + " - " +course.initials, course.nrc]
      end
    end
  end

  def do_assign
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    @user = User.find(params[:id])
    @course = Course.find_by nrc: params[:user]["courses"]
    @course.user_id= @user.id
    respond_to do |format|
      if @course.save
        format.html { redirect_to users_assign_course_path, :notice =>'Curso ' + @course.to_s + ' asignado con exito'}
      else
        format.html { redirect_to users_assign_course_path, :notice =>'Error al asignar curso'}
      end
    end
  end


  def unassign
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    @user = User.find(params[:id])
    @courses = Array.new
    @user.courses.each do |course|
        @courses << [course.nrc.to_s + " - " +course.initials, course.nrc]
    end
  end

  def do_unassign
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    @user = User.find(params[:id])
    @course = Course.find_by nrc: params[:user]["courses"]
    if @user.id == @course.user_id
      @course.user_id= nil
    end
    respond_to do |format|
      if @course.save
        format.html { redirect_to users_unassign_course_path, :notice =>'Curso ' + @course.to_s + ' desasignado con exito'}
      else
        format.html { redirect_to users_unassign_course_path, :notice =>'Error al desasignar curso'}
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/assign.html.erb
<h1>Asignar Cursos a <%= @user.email %></h1>
<%= bootstrap_form_for(@user,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", url: users_do_assign_url) do |f| %>
    <%= f.select :courses ,@courses, { label: "Curso" }, { class: "selectpicker" } %>
    <%= f.form_group do %>
        <%= f.submit "Asignar" %>
    <% end %>
<% end %>

app/views/users/index.html.erb
<h1>Usuarios</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Tipo</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin? ? "Administrador" : "Usuario" %></td>
        <td>
          <ul>
            <li><%= link_to("Asignar Cursos", users_assign_course_path(:id => user.id))%></li>
            <li><%= link_to("Quitar Cursos", users_unassign_course_path(:id => user.id))%></li>
            <li><%= user.admin? ? link_to("Quitar permisos", users_change_rol_path(:id => user.id))
                    : link_to("Hacer Admin", users_change_rol_path(:id => user.id)) %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/myCourses.html.erb
<h1 class="text-center">Mis Cursos</h1>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Curso</th>
    <th>Modulo</th>
    <th>Sala</th>
    <th>Tipo</th>
    <th>Periodo</th>
  </tr>
  </thead>
  <tbody>
  <% @assignation_teacher.each do |assignation| %>
      <tr>
        <td><%= assignation[:course][:initials] %> - <%= assignation[:course][:nrc] %></td>
        <td><%= assignation[:schedule][:module] %></td>
        <td><%= assignation[:classroom][:name] %></td>
        <td><%= assignation[:schedule][:tipo] %></td>
        <td><%= assignation[:schedule][:date].nil? ? "Semestral": assignation[:schedule][:date] %></td>
      </tr>

  <% end %>
  </tbody>
</table>

app/views/users/unassign.html.erb
<h1>Quitar Cursos a <%= @user.email %></h1>
<%= bootstrap_form_for(@user,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", url: users_do_unassign_url) do |f| %>
    <%= f.select :courses ,@courses, { label: "Curso" }, { class: "selectpicker" } %>
    <%= f.form_group do %>
        <%= f.submit "Quitar" %>
    <% end %>
<% end %>