config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'registrarse'}
  get 'user/cursos', to: 'users#myCourses', as: 'users_courses'
  get 'users', to: 'users#index', as: 'users_index'
  get 'users/:id/rol', to: 'users#rol', as: 'users_change_rol'
  get 'users/:id/asignar_curso', to: 'users#assign', as: 'users_assign_course'
  patch 'users/:id/asignacion_curso', to: 'users#do_assign', as: 'users_do_assign'
  get 'users/:id/desasignar_curso', to: 'users#unassign', as: 'users_unassign_course'
  patch 'users/:id/desasignacion_curso', to: 'users#do_unassign', as: 'users_do_unassign'

  get 'schedules/new' => 'schedules#new'
  get 'schedules/deleteAssignation' => 'schedules#deleteAssignation'
  get 'schedules/deleteAssignation/do'=> 'schedules#deleteAssignationDo'
  post 'schedules/create' => 'schedules#create'

  get 'asignaciones'          => 'assignations#select'
  get 'asignaciones/ver'      => 'assignations#show'
  get 'asignaciones/generar'  => 'assignations#generate'
  get 'asignaciones/manual'   => 'assignations#manual_select'
  get 'asignaciones/manual/do'=> 'assignations#manual_do'

  root 'pages#main'

  get 'json/downloadCourses' => 'json#downloadCourses'
  get 'json/downloadClassrooms' => 'json#downloadClassrooms'
  get 'json/downloadSchedules' => 'json#downloadSchedules'
  get 'json/databaseLoad' => 'json#databaseLoad'

  get 'consultas'             => 'consults#index'
  get 'consultas/sala/curso'  => 'consults#classroomByCourseOrSchedule'
  get 'consultas/curso/sala'  => 'consults#courseByClassroomAndSchedule'
  get 'salas/informacion'     => 'consults#show_information'

  get 'estadisticas/'  => 'statistics#show'

end

app/models/assignation.rb
class Assignation < ActiveRecord::Base
	has_one :schedule
	validates_presence_of :schedule_id, :classroom_id
end

app/controllers/assignations_controller.rb
class AssignationsController < ApplicationController
  before_action :authenticate_user!, :except  => [ :show ]
  def show
      @final_assignation = Array.new
      Assignation.all.each do |assignation|
      schedule = Schedule.find(assignation[:schedule_id])
      course = Course.find_by nrc: schedule[:nrc]
      classroom = Classroom.find(assignation[:classroom_id])
      dato = {:course => course, :schedule => schedule, :classroom =>classroom}
      @final_assignation << dato
      end
  end

  def select
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
  end

  def manual_select
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    @schedules = Array.new
    schedules = Schedule.all
    schedules.each do |schedule|
      if !(Assignation.find_by schedule_id: schedule.id)
        @schedules << schedule
      end
    end
  end

  def manual_do
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    schedule = Schedule.find params[:id]
    salas = Classroom.all.sort_by {|h| -h[:capacity]}
    type = schedule.date.nil? ? "cursos" : "pruebas"
    curso = Course.find_by nrc: schedule[:nrc]
    dict = {:nrc=>curso[:nrc], :module => schedule[:module], :vacancy => curso[:vacancy], :date => schedule[:date], :schedule_id =>schedule[:id],:power_n => curso[:power_n],:projector => curso[:projector]}
    assign = nil
    while salas.length > 0 and assign.nil?
      createAssignation type, dict, salas
      assign = Assignation.find_by schedule_id: schedule.id
    end
    respond_to do |format|
      if assign.nil?
        format.html { redirect_to :asignaciones_manual, notice: 'Error al asignar sala' }
      else
        sala = Classroom.find assign.classroom_id
        format.html { redirect_to :asignaciones_manual, notice: 'Sala ' + sala.identifier + ' asignada correctamente al curso ' + curso.nrc.to_s + ' - ' + curso.initials }
      end
    end
  end

  def generate
    raise "not authorized" unless AssignationPolicy.new(current_user, Assignation.new).create?
    #authorize @assignation, :create?

    horarios_cursos = Array.new
    horarios_pruebas = Array.new
    a =  Schedule.all
    a.each do |horario|
      if horario[:date] == nil
        curso = Course.find_by nrc:horario[:nrc]
        dict = {:nrc=>curso[:nrc], :module => horario[:module], :vacancy => curso[:vacancy], :date => horario[:date], :schedule_id =>horario[:id],:power_n => curso[:power_n],:projector => curso[:projector]}
        horarios_cursos << dict
      else
        curso = Course.find_by nrc:horario[:nrc]
        dict = {:nrc=>curso[:nrc], :module => horario[:module], :vacancy => curso[:vacancy], :date => horario[:date], :schedule_id =>horario[:id],:power_n => curso[:power_n],:projector => curso[:projector]}
        horarios_pruebas << dict
      end
    end
    horarios_cursos = horarios_cursos.sort_by {|h| -h[:vacancy]}
    horarios_pruebas= horarios_pruebas.sort_by {|h| -h[:vacancy]}
    salas = Classroom.all.sort_by {|h| -h[:capacity]}
    horarios_cursos.each do |dict|
      createAssignation "cursos", dict, salas
    end
    salas = Classroom.all.sort_by {|h| -h[:capacity]}
    horarios_pruebas.each do |dict|
      createAssignation "pruebas", dict, salas
    end
  end

  def createAssignation type, schedule, salas
    aux=false
    sala = salas.shift
    classroom_filter = Assignation.find_by classroom_id:sala[:id]
    if not classroom_filter
      puts 'La sala no está asignada y la podemos asignar'
      Assignation.create(:classroom_id => sala[:id], :schedule_id =>schedule[:schedule_id])
    else
      asignaciones = Assignation.where(:classroom_id=>sala[:id])
      asignaciones.each do |s_id|
        s = Schedule.find(s_id[:schedule_id])
        case type
          when "cursos"
            if s[:module] == schedule[:module]
              puts 'Sala ya está asignada'
              aux=true
              break
            end
          when "pruebas"
            if s[:module] == schedule[:module] && s[:date]== nil
              puts 'Sala esta ocupada todo el semestre'
              aux=true
              break
            elsif s[:module] == schedule[:module] && s[:date]==schedule[:date]
              puts 'Sala esta ocupada en esa fecha exacta'
              aux=true
              break
            end
          else
            nil
        end
      end
      if not aux
        puts 'Asignar Sala'
        Assignation.create(:classroom_id => sala[:id], :schedule_id =>schedule[:schedule_id])
      end
    end
  end
end

app/helpers/assignations_helper.rb
module AssignationsHelper
end

app/views/assignations/generate.html.erb
<% provide(:title,"Asignacion Completada") %>
<div class="alert alert-success" role="alert">
	<h1>
		La Asignación de cursos a las salas se ha realizado con éxito. En breve será redirigido la lista con todas las asignaciones hechas.
	</h1>
</div>
<script type="text/javascript">
	window.setTimeout(function(){
		window.location = "<%= request.protocol + request.host_with_port %>" + "/asignaciones/ver"
	},5000)
</script>

app/views/assignations/manual_select.html.erb
<h1 class="text-center">Asignar Salas a Curso</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Curso</th>
      <th>Tipo</th>
      <th>Fecha</th>
      <th>Modulo</th>
      <th>Accion</th>
    </tr>
  </thead>
  <tbody>
  <% @schedules.each do |schedule| %>
    <tr>
      <td><%= schedule.nrc %> - <%= (Course.find_by nrc: schedule.nrc).initials %></td>
      <td><%= schedule.date.nil? ? "Semestral" : "Dia"  %></td>
      <td><%= schedule.date.nil? ? "-" : schedule.date  %></td>
      <td><%= schedule.module %></td>
      <td>
        <%= link_to "Asignar Sala", asignaciones_manual_do_path(:id => schedule.id), :class => "btn btn-default"  %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/assignations/select.html.erb
<ul>
  <li><%= link_to "Manual", asignaciones_manual_path %></li>
  <li><%= link_to "Automático", asignaciones_generar_path %></li>
</ul>

app/views/assignations/show.html.erb
<% provide(:title,"Salas Asignadas") %>
<h1 class="text-center"> Salas Asignadas</h1>
<table class="table table-bordered" style="color: #000;">
<thead>
<tr>
	<th>Modulo</th>
	<th>Curso</th>
	<th style="min-width: 160px">Requerimientos</th>
	<th>Sala</th>
	<th style="min-width: 160px" >Caracteristicas</th>
	<th>Problema</th>
</tr>
</thead>
<tbody>
<% @final_assignation.each do |a| %>
	<tr class="<% if  (a[:course][:vacancy]  > a[:classroom][:capacity]) or 
						(a[:course][:power_n] > a[:classroom][:power_n]) or
						(a[:course][:projector] == true and a[:classroom][:projector] == false )
						%> danger <% end %>">
		<td><%= a[:schedule][:module] %></td>
		<td><%= a[:course][:nrc].to_s + " - " + a[:course][:initials] %></td>
		<td>
			<ul class="list-unstyled">
				<li><b>Cupos</b>: <%= a[:course][:vacancy] %></li>
				<li><b>Enchufes</b>: <%= a[:course][:power_n] %></li>
				<li><b>Proyector</b>: <%= a[:course][:projector] == true ? "Si" : "No" %></li>
			</ul>
		</td>
		<td><%= a[:classroom][:name] %></td>
		<td>
			<ul class="list-unstyled">
				<li><b>Capacidad</b>: <%= a[:classroom][:capacity] %></li>
				<li><b>Enchufes</b>: <%= a[:classroom][:power_n] %></li>
				<li><b>Proyector</b>: <%= a[:classroom][:projector] == true ? "Si" : "No" %></li>
			</ul>
		</td>
		<td>
			<ul> 
				<% if a[:course][:vacancy]  > a[:classroom][:capacity] %>
				<li> La capacidad del curso excede la capacidad de la sala</li>
				<% end %>
				<% if a[:course][:power_n] > a[:classroom][:power_n] %>
				<li> La cantidad de enchufes necesarios excede los disponibles en la sala</li>
				<% end %>
				<% if a[:course][:projector] == true and a[:classroom][:projector] == false %>
				<li> El curso requiere proyector y la sala no lo posee </li>
				<% end %>
			</ul>
		</td>
	</tr>
<% end %>
</tbody>
</table>