config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'registrarse'}
  get 'user/cursos', to: 'users#myCourses', as: 'users_courses'
  get 'users', to: 'users#index', as: 'users_index'
  get 'users/:id/rol', to: 'users#rol', as: 'users_change_rol'
  get 'users/:id/asignar_curso', to: 'users#assign', as: 'users_assign_course'
  patch 'users/:id/asignacion_curso', to: 'users#do_assign', as: 'users_do_assign'
  get 'users/:id/desasignar_curso', to: 'users#unassign', as: 'users_unassign_course'
  patch 'users/:id/desasignacion_curso', to: 'users#do_unassign', as: 'users_do_unassign'

  get 'schedules/new' => 'schedules#new'
  get 'schedules/deleteAssignation' => 'schedules#deleteAssignation'
  get 'schedules/deleteAssignation/do'=> 'schedules#deleteAssignationDo'
  post 'schedules/create' => 'schedules#create'

  get 'asignaciones'          => 'assignations#select'
  get 'asignaciones/ver'      => 'assignations#show'
  get 'asignaciones/generar'  => 'assignations#generate'
  get 'asignaciones/manual'   => 'assignations#manual_select'
  get 'asignaciones/manual/do'=> 'assignations#manual_do'

  root 'pages#main'

  get 'json/downloadCourses' => 'json#downloadCourses'
  get 'json/downloadClassrooms' => 'json#downloadClassrooms'
  get 'json/downloadSchedules' => 'json#downloadSchedules'
  get 'json/databaseLoad' => 'json#databaseLoad'

  get 'consultas'             => 'consults#index'
  get 'consultas/sala/curso'  => 'consults#classroomByCourseOrSchedule'
  get 'consultas/curso/sala'  => 'consults#courseByClassroomAndSchedule'
  get 'salas/informacion'     => 'consults#show_information'

  get 'estadisticas/'  => 'statistics#show'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= set_title(yield(:title)) %></title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <!-- fontAwesome css -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- bootstrap css -->
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if not current_page? root_path %>
      <style>
        body{
          padding-top: 90px;
        }
      </style>
  <% end %>
  <!-- Mobile Specific Meta -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSS
		================================================== -->

  <!-- bootstrap.min  PARA SLIDER --
  <link rel="stylesheet" href="css/slit-slider.scss">
  <!-- Main Stylesheet --
  <link rel="stylesheet" href="css/main.css">
  <!-- Modernizer Script for old Browsers --
  <script src="js/modernizr-2.6.2.min.js"></script>
  -->
</head>
<body id="body">
<!-- preloader -->
<div id="preloader">
  <div class="loder-box">
    <div class="battery"></div>
  </div>
</div>
<!-- end preloader -->
<!--
        Fixed Navigation
        ==================================== -->
<header id="navigation" class="navbar-inverse navbar-fixed-top animated-header">
    <% if notice %>
  <div class="alert alert-success text-center" id="notificacion" role="alert">
      <%= notice %>
  </div>
  <% end %>
  <div class="container">
    <div class="navbar-header">
      <!-- responsive nav button -->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- /responsive nav button -->

      <!-- logo -->
      <h1 class="navbar-brand">
        <%= link_to "Salas UC", root_path(anchor: 'body') %>
      </h1>
      <!-- /logo -->
    </div>

    <!-- main nav -->
    <nav class="collapse navbar-collapse navbar-right" role="navigation">
      <ul id="nav" class="nav navbar-nav">
        <li><%= link_to "Inicio", root_path(anchor: 'body') %></li>
        <li><%= link_to "Servicios", root_path(anchor: 'service') %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Herramientas", root_path(anchor: 'tools') %></li>
        <li><%= link_to "Desconectarse", destroy_user_session_path, :method => :delete %></li>
        <li><%= link_to('Mi Cuenta', root_path(anchor: 'account')) %></li>
        <li style="padding: 15px">Hola  <%= current_user.email %> - <% if current_user.admin? %><i class="fa fa-key"></i><% else %><i class="fa fa-graduation-cap"></i><% end %></li>
        <% else %>
        <li><%= link_to('Autenticarse', root_path(anchor: 'account')) %></li>
        <li><%= link_to('Registrarse', root_path(anchor: 'account')) %></li>
        <% end %>
      </ul>
    </nav>
    <!-- /main nav -->


  </div>
</header>
<!--
End Fixed Navigation
==================================== -->

<main class="site-content" role="main">
  <% if not current_page? root_path %>
      <div class="container">
  <% end %>
  <%= yield %>
  <% if not current_page? root_path %>
      </div>
  <% end %>
</main>
<footer id="footer">
  <div class="container">
    <div class="row text-center">
      <div class="footer-content">
        <p>Desarrollado por <a href="https://github.com/IIC2143-2016-1/Blank">Blank</a></p>
        <p><strong>Blue Onepage</strong> Design and Developed By<a href="http://www.themefisher.com">Themefisher</a> </p>
      </div>
    </div>
  </div>
</footer>

<!-- Essential jQuery Plugins
================================================== -->

<!-- Bootstrap -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script>
  $(document).ready(function () {
      if($('main').height() < 500){
        $('main').height(550);
      }
  })
</script>
<% if notice %>
<script>
  $(document).ready(
  setTimeout(function () {
    $('#notificacion').fadeOut()
  }, 3000)
  )
</script>
<% end %>
<!-- Single Page Nav BAJAR DE A POCO --
<script src="js/jquery.singlePageNav.min.js"></script>
<!-- jquery easing BAJAR DE APOCO--
<script src="js/jquery.easing.min.js"></script>
<!-- Fullscreen slider --
<script src="js/jquery.slitslider.js"></script>
<script src="js/jquery.ba-cond.min.js"></script>
<!-- Custom Functions --
<script src="js/main.js"></script>
-->
</body>
</html>

app/views/layouts/testing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Jquery -->
  <script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI=" crossorigin="anonymous"></script>
  <!-- Bootstrap -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <!-- fontAwesome css -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- bootstrap css -->
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
</head>
<body>

        <nav id="main-menu" class="navbar navbar-default navbar-fixed-top" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"><img src="images/logo.png" alt="logo"></a>
                </div>
        
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li><%= link_to "Inicio", root_path %></li>
                        <% if user_signed_in? %>
                        <li><%= link_to('Mi Perfil', edit_user_registration_path) %></li>
                        <li><%= link_to "Salir", destroy_user_session_path, :method => :delete %></li>
                        <% else %>
                        <li><a href="#" id="btn-login">Entrar</a></li>
                        <li><a href="#" id="btn-register">Registrarse</a></li>
                        <% end %>                        
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->


<div class="black-back sign"></div>
<div class="sign-back center-block sign">
  <div class="container-fluid sign" id="login">
          <h1 class="text-center">Log In</h1>
          <%= bootstrap_form_for(resource, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", as: resource_name, url: session_path(resource_name)) do |f| %>
            <%= f.email_field :email, required: false, autofocus: true %>
            <%= f.password_field :password, required: false %>
            <%= f.form_group do %>
            <%= f.check_box :remember_me, as: :boolean if devise_mapping.rememberable? %>
              <% end %>
            <%= f.form_group do %>
              <%= f.submit "Log in" %>
              <% end %>
          <% end %>
            <div class="container-fluid">
              <div class="row">
                <div class="col-sm-10 col-sm-offset-2">
                  <%= render "devise/shared/links" %>
                </div>
              </div>
            </div>
  </div>
  <div class="container-fluid sign" id="register">
            <h2 class="text-center">Sign up</h2>
            <%= bootstrap_form_for(resource,layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10", as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= f.email_field :email, required: true, autofocus: true %>
                <%= f.password_field :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                <%= f.password_field :password_confirmation, required: true %>
                <%= f.form_group do %>
                <%= f.submit "Registrarse" %>
                <% end %>
            <% end %>
              <div class="container-fluid">
                <div class="row">
                  <div class="col-sm-10 col-sm-offset-2">
              <%= render "devise/shared/links" %>
                  </div>
                </div>
              </div>
              </div>
            </div>

<div class="container">
    <%= yield %>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    $('.sign').hide();
  })

  $('#btn-login').click(function (){
    $('.black-back').fadeIn();
    $('.sign-back').fadeIn();
    $('#login').fadeIn();
    $('#register').hide();
})
  $('#btn-register').click(function (){
    $('.black-back').fadeIn();
    $('.sign-back').fadeIn();
    $('#login').hide();
    $('#register').fadeIn();
})
  $('.black-back').click(closeSignBack);
  function closeSignBack() {
    $('.black-back').fadeOut();
    $('.sign-back').fadeOut();
  }
</script>
</body>
</html>